name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-formatting:
    name: Check Nix formatting
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check formatting
        run: nix fmt -- --check .

  check-lint:
    name: Lint Nix code
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run statix
        run: nix shell nixpkgs#statix -c statix check
